### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by NikoLieberum** [NikoLieberum/HomeBrewer#1]
* [ ] Kotin vs. Java - Yorick & Niko
* [ ] GitHub - Niko
* [ ] UI Design - Yorick & Niko
* [ ] Funktionen und Infos - Yorick
* [ ] Ordnerstruktur - Niko
* [ ] Namen Ideen - Yorick & Niko
* [ ] Template - Niko
